export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const DECREMENT_PAGE = 'DECREMENT_PAGE';
export const RESET_PAGE = 'RESET_PAGE';
export const ASSIGN_SEARCH_QUERY = 'ASSIGN_SEARCH_QUERY';